### ISSUE TITLE
Coping and deleting frames

### ISSUE THREAD

**Issue by crocodile54** [topshed/RPi_8x8GridDraw#7]
I drew a picture on frame one, then I tried to copy it, nothing happened. So I created a new frame and tried to copy that. Then I tried deleting the copied frame, however it cleared my original frame as well as deleting the others.

**Comment by crocodile54** [comment]
If I try and delete frame 001 this happens:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.5/dist-packages/guizero/PushButton.py", line 146, in _command_callback
    self._command()
  File "8x8grid-guizero.py", line 186, in left
    load_frame()
  File "8x8grid-guizero.py", line 132, in load_frame
    sh.set_pixels(frames[current_frame_number])
KeyError: 1
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.5/dist-packages/guizero/PushButton.py", line 146, in _command_callback
    self._command()
  File "8x8grid-guizero.py", line 122, in delete_frame
    del frames[len(frames)]
KeyError: 1

**Comment by crocodile54** [comment]
If I try and delete the last frames this happens:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.5/dist-packages/guizero/PushButton.py", line 146, in _command_callback
    self._command()
  File "8x8grid-guizero.py", line 186, in left
    load_frame()
  File "8x8grid-guizero.py", line 132, in load_frame
    sh.set_pixels(frames[current_frame_number])
KeyError: 3
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.5/dist-packages/guizero/PushButton.py", line 146, in _command_callback
    self._command()
  File "8x8grid-guizero.py", line 186, in left
    load_frame()
  File "8x8grid-guizero.py", line 132, in load_frame
    sh.set_pixels(frames[current_frame_number])
KeyError: 2

**Comment by crocodile54** [comment]
Also if I try and go back to the original frame after I have deleted the rest I get this:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.5/dist-packages/guizero/PushButton.py", line 146, in _command_callback
    self._command()
  File "8x8grid-guizero.py", line 122, in delete_frame
    del frames[len(frames)]
KeyError: 3
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.5/dist-packages/guizero/PushButton.py", line 146, in _command_callback
    self._command()
  File "8x8grid-guizero.py", line 120, in delete_frame
    frames[f] = frames[f+1].copy()
KeyError: 3

**Comment by crocodile54** [comment]
If I deleted frame 001 this happens:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.5/dist-packages/guizero/PushButton.py", line 146, in _command_callback
    self._command()
  File "8x8grid-guizero.py", line 123, in delete_frame
    load_frame()
  File "8x8grid-guizero.py", line 132, in load_frame
    sh.set_pixels(frames[current_frame_number])
KeyError: 1

**Comment by topshed** [comment]
I think this is the same as issue #6 - now fixed
